# Generated by Django 6.1.1 on 2026-09-29 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=20)),
                ('file_path', models.TextField(unique=True)),
                ('folder_name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('local', 'Local (HD/USB)'), ('google_drive', 'Google Drive')], default='local', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('indexed', 'Indexado'), ('error', 'Erro'), ('removed', 'Removido')], default='pending', max_length=20)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arquivo Indexado',
                'verbose_name_plural': 'Arquivos Indexados',
                'indexes': [models.Index(fields=['source', 'status'], name='finder_file_source_ce1439_idx'), models.Index(fields=['file_hash'], name='finder_file_file_ha_b83d61_idx'), models.Index(fields=['extension'], name='finder_file_extensi_81df21_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('slide_number', models.IntegerField(blank=True, null=True)),
                ('snippet_text', models.TextField()),
                ('normalized_text', models.TextField(db_index=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='finder_files.indexedfile')),
            ],
            options={
                'verbose_name': 'Trecho do Documento',
                'verbose_name_plural': 'Trechos dos Documentos',
                'indexes': [models.Index(fields=['indexed_file', 'page_number'], name='finder_file_indexed_86ed57_idx'), models.Index(fields=['indexed_file', 'slide_number'], name='finder_file_indexed_61f887_idx')],
            },
        ),
    ]
